# infra/docker/Dockerfile.storefront
FROM node:20-alpine AS builder

WORKDIR /app
RUN npm install -g pnpm
COPY . .
RUN pnpm install
RUN pnpm build:storefront

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/apps/storefront/.next/standalone ./
COPY --from=builder /app/apps/storefront/.next/static ./apps/storefront/.next/static
COPY --from=builder /app/apps/storefront/public ./apps/storefront/public

EXPOSE 3000
ENV PORT 3000
CMD ["node", "server.js"]
